[package]
name = "cloak-miner"
version = "0.1.0"
edition = "2021"
description = "Standalone PoW miner for Cloak protocol (Ore-style)"
license = "MIT"

[[bin]]
name = "cloak-miner"
path = "src/main.rs"

[dependencies]
# CLI
clap = { version = "4.4", features = ["derive", "env"] }
dotenvy = "0.15"

# Solana
solana-sdk = { workspace = true }
solana-client = "=2.3.1"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Cryptography
blake3 = "1.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Time
chrono = "0.4"

# Configuration
config = "0.13"

# Signal handling
ctrlc = "3.4"

# Shell expansion
shellexpand = "3.1"
solana-system-interface = "2.0.0"

[dev-dependencies]
tempfile = "3.0"
